/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors/index'
import { Route as ClinicsIndexRouteImport } from './routes/clinics/index'
import { Route as TreatmentsTreatmentSlugRouteImport } from './routes/treatments/$treatmentSlug'
import { Route as DoctorsDoctorSlugRouteImport } from './routes/doctors/$doctorSlug'
import { Route as ClinicsClinicSlugRouteImport } from './routes/clinics/$clinicSlug'
import { Route as BookClinicSlugRouteImport } from './routes/book/$clinicSlug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as ClinicClinicSlugIndexRouteImport } from './routes/clinic/$clinicSlug/index'
import { Route as ClinicClinicSlugTeamRouteImport } from './routes/clinic/$clinicSlug/team'
import { Route as ClinicClinicSlugServicesRouteImport } from './routes/clinic/$clinicSlug/services'
import { Route as ClinicClinicSlugContactRouteImport } from './routes/clinic/$clinicSlug/contact'
import { Route as AdminAuthenticatedWebsiteRouteImport } from './routes/admin/_authenticated/website'
import { Route as AdminAuthenticatedSettingsRouteImport } from './routes/admin/_authenticated/settings'
import { Route as AdminAuthenticatedPatientsRouteImport } from './routes/admin/_authenticated/patients'
import { Route as AdminAuthenticatedDoctorsRouteImport } from './routes/admin/_authenticated/doctors'
import { Route as AdminAuthenticatedDashboardRouteImport } from './routes/admin/_authenticated/dashboard'
import { Route as AdminAuthenticatedAppointmentsRouteImport } from './routes/admin/_authenticated/appointments'
import { Route as ClinicClinicSlugBlogIndexRouteImport } from './routes/clinic/$clinicSlug/blog/index'
import { Route as ClinicClinicSlugBlogPostSlugRouteImport } from './routes/clinic/$clinicSlug/blog/$postSlug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsIndexRoute = ClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsTreatmentSlugRoute = TreatmentsTreatmentSlugRouteImport.update({
  id: '/treatments/$treatmentSlug',
  path: '/treatments/$treatmentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorSlugRoute = DoctorsDoctorSlugRouteImport.update({
  id: '/doctors/$doctorSlug',
  path: '/doctors/$doctorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsClinicSlugRoute = ClinicsClinicSlugRouteImport.update({
  id: '/clinics/$clinicSlug',
  path: '/clinics/$clinicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookClinicSlugRoute = BookClinicSlugRouteImport.update({
  id: '/book/$clinicSlug',
  path: '/book/$clinicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicClinicSlugIndexRoute = ClinicClinicSlugIndexRouteImport.update({
  id: '/clinic/$clinicSlug/',
  path: '/clinic/$clinicSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicClinicSlugTeamRoute = ClinicClinicSlugTeamRouteImport.update({
  id: '/clinic/$clinicSlug/team',
  path: '/clinic/$clinicSlug/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicClinicSlugServicesRoute =
  ClinicClinicSlugServicesRouteImport.update({
    id: '/clinic/$clinicSlug/services',
    path: '/clinic/$clinicSlug/services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClinicClinicSlugContactRoute = ClinicClinicSlugContactRouteImport.update({
  id: '/clinic/$clinicSlug/contact',
  path: '/clinic/$clinicSlug/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedWebsiteRoute =
  AdminAuthenticatedWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedSettingsRoute =
  AdminAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedPatientsRoute =
  AdminAuthenticatedPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedDoctorsRoute =
  AdminAuthenticatedDoctorsRouteImport.update({
    id: '/doctors',
    path: '/doctors',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedDashboardRoute =
  AdminAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedAppointmentsRoute =
  AdminAuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const ClinicClinicSlugBlogIndexRoute =
  ClinicClinicSlugBlogIndexRouteImport.update({
    id: '/clinic/$clinicSlug/blog/',
    path: '/clinic/$clinicSlug/blog/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClinicClinicSlugBlogPostSlugRoute =
  ClinicClinicSlugBlogPostSlugRouteImport.update({
    id: '/clinic/$clinicSlug/blog/$postSlug',
    path: '/clinic/$clinicSlug/blog/$postSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/book/$clinicSlug': typeof BookClinicSlugRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/admin/appointments': typeof AdminAuthenticatedAppointmentsRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/doctors': typeof AdminAuthenticatedDoctorsRoute
  '/admin/patients': typeof AdminAuthenticatedPatientsRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/website': typeof AdminAuthenticatedWebsiteRoute
  '/clinic/$clinicSlug/contact': typeof ClinicClinicSlugContactRoute
  '/clinic/$clinicSlug/services': typeof ClinicClinicSlugServicesRoute
  '/clinic/$clinicSlug/team': typeof ClinicClinicSlugTeamRoute
  '/clinic/$clinicSlug/': typeof ClinicClinicSlugIndexRoute
  '/clinic/$clinicSlug/blog/$postSlug': typeof ClinicClinicSlugBlogPostSlugRoute
  '/clinic/$clinicSlug/blog/': typeof ClinicClinicSlugBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/book/$clinicSlug': typeof BookClinicSlugRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics': typeof ClinicsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
  '/admin/appointments': typeof AdminAuthenticatedAppointmentsRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/doctors': typeof AdminAuthenticatedDoctorsRoute
  '/admin/patients': typeof AdminAuthenticatedPatientsRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/website': typeof AdminAuthenticatedWebsiteRoute
  '/clinic/$clinicSlug/contact': typeof ClinicClinicSlugContactRoute
  '/clinic/$clinicSlug/services': typeof ClinicClinicSlugServicesRoute
  '/clinic/$clinicSlug/team': typeof ClinicClinicSlugTeamRoute
  '/clinic/$clinicSlug': typeof ClinicClinicSlugIndexRoute
  '/clinic/$clinicSlug/blog/$postSlug': typeof ClinicClinicSlugBlogPostSlugRoute
  '/clinic/$clinicSlug/blog': typeof ClinicClinicSlugBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/book/$clinicSlug': typeof BookClinicSlugRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
  '/admin/_authenticated/appointments': typeof AdminAuthenticatedAppointmentsRoute
  '/admin/_authenticated/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/_authenticated/doctors': typeof AdminAuthenticatedDoctorsRoute
  '/admin/_authenticated/patients': typeof AdminAuthenticatedPatientsRoute
  '/admin/_authenticated/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/_authenticated/website': typeof AdminAuthenticatedWebsiteRoute
  '/clinic/$clinicSlug/contact': typeof ClinicClinicSlugContactRoute
  '/clinic/$clinicSlug/services': typeof ClinicClinicSlugServicesRoute
  '/clinic/$clinicSlug/team': typeof ClinicClinicSlugTeamRoute
  '/clinic/$clinicSlug/': typeof ClinicClinicSlugIndexRoute
  '/clinic/$clinicSlug/blog/$postSlug': typeof ClinicClinicSlugBlogPostSlugRoute
  '/clinic/$clinicSlug/blog/': typeof ClinicClinicSlugBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/admin'
    | '/admin/login'
    | '/book/$clinicSlug'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics/'
    | '/doctors/'
    | '/treatments/'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/settings'
    | '/admin/website'
    | '/clinic/$clinicSlug/contact'
    | '/clinic/$clinicSlug/services'
    | '/clinic/$clinicSlug/team'
    | '/clinic/$clinicSlug/'
    | '/clinic/$clinicSlug/blog/$postSlug'
    | '/clinic/$clinicSlug/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/admin'
    | '/admin/login'
    | '/book/$clinicSlug'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics'
    | '/doctors'
    | '/treatments'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/settings'
    | '/admin/website'
    | '/clinic/$clinicSlug/contact'
    | '/clinic/$clinicSlug/services'
    | '/clinic/$clinicSlug/team'
    | '/clinic/$clinicSlug'
    | '/clinic/$clinicSlug/blog/$postSlug'
    | '/clinic/$clinicSlug/blog'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/book/$clinicSlug'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics/'
    | '/doctors/'
    | '/treatments/'
    | '/admin/_authenticated/appointments'
    | '/admin/_authenticated/dashboard'
    | '/admin/_authenticated/doctors'
    | '/admin/_authenticated/patients'
    | '/admin/_authenticated/settings'
    | '/admin/_authenticated/website'
    | '/clinic/$clinicSlug/contact'
    | '/clinic/$clinicSlug/services'
    | '/clinic/$clinicSlug/team'
    | '/clinic/$clinicSlug/'
    | '/clinic/$clinicSlug/blog/$postSlug'
    | '/clinic/$clinicSlug/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BookClinicSlugRoute: typeof BookClinicSlugRoute
  ClinicsClinicSlugRoute: typeof ClinicsClinicSlugRoute
  DoctorsDoctorSlugRoute: typeof DoctorsDoctorSlugRoute
  TreatmentsTreatmentSlugRoute: typeof TreatmentsTreatmentSlugRoute
  ClinicsIndexRoute: typeof ClinicsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
  ClinicClinicSlugContactRoute: typeof ClinicClinicSlugContactRoute
  ClinicClinicSlugServicesRoute: typeof ClinicClinicSlugServicesRoute
  ClinicClinicSlugTeamRoute: typeof ClinicClinicSlugTeamRoute
  ClinicClinicSlugIndexRoute: typeof ClinicClinicSlugIndexRoute
  ClinicClinicSlugBlogPostSlugRoute: typeof ClinicClinicSlugBlogPostSlugRoute
  ClinicClinicSlugBlogIndexRoute: typeof ClinicClinicSlugBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/': {
      id: '/clinics/'
      path: '/clinics'
      fullPath: '/clinics/'
      preLoaderRoute: typeof ClinicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$treatmentSlug': {
      id: '/treatments/$treatmentSlug'
      path: '/treatments/$treatmentSlug'
      fullPath: '/treatments/$treatmentSlug'
      preLoaderRoute: typeof TreatmentsTreatmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorSlug': {
      id: '/doctors/$doctorSlug'
      path: '/doctors/$doctorSlug'
      fullPath: '/doctors/$doctorSlug'
      preLoaderRoute: typeof DoctorsDoctorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/$clinicSlug': {
      id: '/clinics/$clinicSlug'
      path: '/clinics/$clinicSlug'
      fullPath: '/clinics/$clinicSlug'
      preLoaderRoute: typeof ClinicsClinicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$clinicSlug': {
      id: '/book/$clinicSlug'
      path: '/book/$clinicSlug'
      fullPath: '/book/$clinicSlug'
      preLoaderRoute: typeof BookClinicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/$clinicSlug/': {
      id: '/clinic/$clinicSlug/'
      path: '/clinic/$clinicSlug'
      fullPath: '/clinic/$clinicSlug/'
      preLoaderRoute: typeof ClinicClinicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/$clinicSlug/team': {
      id: '/clinic/$clinicSlug/team'
      path: '/clinic/$clinicSlug/team'
      fullPath: '/clinic/$clinicSlug/team'
      preLoaderRoute: typeof ClinicClinicSlugTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/$clinicSlug/services': {
      id: '/clinic/$clinicSlug/services'
      path: '/clinic/$clinicSlug/services'
      fullPath: '/clinic/$clinicSlug/services'
      preLoaderRoute: typeof ClinicClinicSlugServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/$clinicSlug/contact': {
      id: '/clinic/$clinicSlug/contact'
      path: '/clinic/$clinicSlug/contact'
      fullPath: '/clinic/$clinicSlug/contact'
      preLoaderRoute: typeof ClinicClinicSlugContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/website': {
      id: '/admin/_authenticated/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminAuthenticatedWebsiteRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/settings': {
      id: '/admin/_authenticated/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthenticatedSettingsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/patients': {
      id: '/admin/_authenticated/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminAuthenticatedPatientsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/doctors': {
      id: '/admin/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminAuthenticatedDoctorsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/dashboard': {
      id: '/admin/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthenticatedDashboardRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/appointments': {
      id: '/admin/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAuthenticatedAppointmentsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/clinic/$clinicSlug/blog/': {
      id: '/clinic/$clinicSlug/blog/'
      path: '/clinic/$clinicSlug/blog'
      fullPath: '/clinic/$clinicSlug/blog/'
      preLoaderRoute: typeof ClinicClinicSlugBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/$clinicSlug/blog/$postSlug': {
      id: '/clinic/$clinicSlug/blog/$postSlug'
      path: '/clinic/$clinicSlug/blog/$postSlug'
      fullPath: '/clinic/$clinicSlug/blog/$postSlug'
      preLoaderRoute: typeof ClinicClinicSlugBlogPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedAppointmentsRoute: typeof AdminAuthenticatedAppointmentsRoute
  AdminAuthenticatedDashboardRoute: typeof AdminAuthenticatedDashboardRoute
  AdminAuthenticatedDoctorsRoute: typeof AdminAuthenticatedDoctorsRoute
  AdminAuthenticatedPatientsRoute: typeof AdminAuthenticatedPatientsRoute
  AdminAuthenticatedSettingsRoute: typeof AdminAuthenticatedSettingsRoute
  AdminAuthenticatedWebsiteRoute: typeof AdminAuthenticatedWebsiteRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedAppointmentsRoute: AdminAuthenticatedAppointmentsRoute,
  AdminAuthenticatedDashboardRoute: AdminAuthenticatedDashboardRoute,
  AdminAuthenticatedDoctorsRoute: AdminAuthenticatedDoctorsRoute,
  AdminAuthenticatedPatientsRoute: AdminAuthenticatedPatientsRoute,
  AdminAuthenticatedSettingsRoute: AdminAuthenticatedSettingsRoute,
  AdminAuthenticatedWebsiteRoute: AdminAuthenticatedWebsiteRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BookClinicSlugRoute: BookClinicSlugRoute,
  ClinicsClinicSlugRoute: ClinicsClinicSlugRoute,
  DoctorsDoctorSlugRoute: DoctorsDoctorSlugRoute,
  TreatmentsTreatmentSlugRoute: TreatmentsTreatmentSlugRoute,
  ClinicsIndexRoute: ClinicsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
  ClinicClinicSlugContactRoute: ClinicClinicSlugContactRoute,
  ClinicClinicSlugServicesRoute: ClinicClinicSlugServicesRoute,
  ClinicClinicSlugTeamRoute: ClinicClinicSlugTeamRoute,
  ClinicClinicSlugIndexRoute: ClinicClinicSlugIndexRoute,
  ClinicClinicSlugBlogPostSlugRoute: ClinicClinicSlugBlogPostSlugRoute,
  ClinicClinicSlugBlogIndexRoute: ClinicClinicSlugBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
