/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors/index'
import { Route as ClinicsIndexRouteImport } from './routes/clinics/index'
import { Route as TreatmentsTreatmentSlugRouteImport } from './routes/treatments/$treatmentSlug'
import { Route as DoctorsDoctorSlugRouteImport } from './routes/doctors/$doctorSlug'
import { Route as ClinicsClinicSlugRouteImport } from './routes/clinics/$clinicSlug'
import { Route as BookClinicSlugRouteImport } from './routes/book/$clinicSlug'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsIndexRoute = ClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsTreatmentSlugRoute = TreatmentsTreatmentSlugRouteImport.update({
  id: '/treatments/$treatmentSlug',
  path: '/treatments/$treatmentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorSlugRoute = DoctorsDoctorSlugRouteImport.update({
  id: '/doctors/$doctorSlug',
  path: '/doctors/$doctorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsClinicSlugRoute = ClinicsClinicSlugRouteImport.update({
  id: '/clinics/$clinicSlug',
  path: '/clinics/$clinicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookClinicSlugRoute = BookClinicSlugRouteImport.update({
  id: '/book/$clinicSlug',
  path: '/book/$clinicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$clinicSlug': typeof BookClinicSlugRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$clinicSlug': typeof BookClinicSlugRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics': typeof ClinicsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$clinicSlug': typeof BookClinicSlugRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/settings'
    | '/book/$clinicSlug'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics/'
    | '/doctors/'
    | '/treatments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/settings'
    | '/book/$clinicSlug'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics'
    | '/doctors'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/login'
    | '/admin/settings'
    | '/book/$clinicSlug'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics/'
    | '/doctors/'
    | '/treatments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  BookClinicSlugRoute: typeof BookClinicSlugRoute
  ClinicsClinicSlugRoute: typeof ClinicsClinicSlugRoute
  DoctorsDoctorSlugRoute: typeof DoctorsDoctorSlugRoute
  TreatmentsTreatmentSlugRoute: typeof TreatmentsTreatmentSlugRoute
  ClinicsIndexRoute: typeof ClinicsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/': {
      id: '/clinics/'
      path: '/clinics'
      fullPath: '/clinics/'
      preLoaderRoute: typeof ClinicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$treatmentSlug': {
      id: '/treatments/$treatmentSlug'
      path: '/treatments/$treatmentSlug'
      fullPath: '/treatments/$treatmentSlug'
      preLoaderRoute: typeof TreatmentsTreatmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorSlug': {
      id: '/doctors/$doctorSlug'
      path: '/doctors/$doctorSlug'
      fullPath: '/doctors/$doctorSlug'
      preLoaderRoute: typeof DoctorsDoctorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/$clinicSlug': {
      id: '/clinics/$clinicSlug'
      path: '/clinics/$clinicSlug'
      fullPath: '/clinics/$clinicSlug'
      preLoaderRoute: typeof ClinicsClinicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$clinicSlug': {
      id: '/book/$clinicSlug'
      path: '/book/$clinicSlug'
      fullPath: '/book/$clinicSlug'
      preLoaderRoute: typeof BookClinicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  BookClinicSlugRoute: BookClinicSlugRoute,
  ClinicsClinicSlugRoute: ClinicsClinicSlugRoute,
  DoctorsDoctorSlugRoute: DoctorsDoctorSlugRoute,
  TreatmentsTreatmentSlugRoute: TreatmentsTreatmentSlugRoute,
  ClinicsIndexRoute: ClinicsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
