/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClinicsIndexRouteImport } from './routes/clinics/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors/index'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TreatmentsTreatmentSlugRouteImport } from './routes/treatments/$treatmentSlug'
import { Route as DoctorsDoctorSlugRouteImport } from './routes/doctors/$doctorSlug'
import { Route as ClinicsClinicSlugRouteImport } from './routes/clinics/$clinicSlug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsIndexRoute = ClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsTreatmentSlugRoute = TreatmentsTreatmentSlugRouteImport.update({
  id: '/treatments/$treatmentSlug',
  path: '/treatments/$treatmentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorSlugRoute = DoctorsDoctorSlugRouteImport.update({
  id: '/doctors/$doctorSlug',
  path: '/doctors/$doctorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsClinicSlugRoute = ClinicsClinicSlugRouteImport.update({
  id: '/clinics/$clinicSlug',
  path: '/clinics/$clinicSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics': typeof ClinicsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/clinics/$clinicSlug': typeof ClinicsClinicSlugRoute
  '/doctors/$doctorSlug': typeof DoctorsDoctorSlugRoute
  '/treatments/$treatmentSlug': typeof TreatmentsTreatmentSlugRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics/'
    | '/doctors/'
    | '/treatments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics'
    | '/doctors'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/clinics/$clinicSlug'
    | '/doctors/$doctorSlug'
    | '/treatments/$treatmentSlug'
    | '/clinics/'
    | '/doctors/'
    | '/treatments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  ClinicsClinicSlugRoute: typeof ClinicsClinicSlugRoute
  DoctorsDoctorSlugRoute: typeof DoctorsDoctorSlugRoute
  TreatmentsTreatmentSlugRoute: typeof TreatmentsTreatmentSlugRoute
  ClinicsIndexRoute: typeof ClinicsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/': {
      id: '/clinics/'
      path: '/clinics'
      fullPath: '/clinics/'
      preLoaderRoute: typeof ClinicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$treatmentSlug': {
      id: '/treatments/$treatmentSlug'
      path: '/treatments/$treatmentSlug'
      fullPath: '/treatments/$treatmentSlug'
      preLoaderRoute: typeof TreatmentsTreatmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorSlug': {
      id: '/doctors/$doctorSlug'
      path: '/doctors/$doctorSlug'
      fullPath: '/doctors/$doctorSlug'
      preLoaderRoute: typeof DoctorsDoctorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/$clinicSlug': {
      id: '/clinics/$clinicSlug'
      path: '/clinics/$clinicSlug'
      fullPath: '/clinics/$clinicSlug'
      preLoaderRoute: typeof ClinicsClinicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  ClinicsClinicSlugRoute: ClinicsClinicSlugRoute,
  DoctorsDoctorSlugRoute: DoctorsDoctorSlugRoute,
  TreatmentsTreatmentSlugRoute: TreatmentsTreatmentSlugRoute,
  ClinicsIndexRoute: ClinicsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
